development:
  secret_key_base: key
  publishable_key: pk_test_51HMg0FFYK0GPyOw5UIAY3ZlTB9ezOGgIUGNdojYTc0pUukBEXSjGmxVDIzMFYOKR8IKf7a0dOcb8GCMKxGqG2fMt00He7cyq4B
  secret_key: sk_test_51HMg0FFYK0GPyOw5sC7r1zpU70xSKUkshzFo2nVR7FsAc09CWpKvg86fFvWInD8pENKfTnM9ZT7ECwdCz7AWIb1v0002DoYZZO
 

test:
  secret_key_base: key
  production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  publishable_key: <%= ENV["publishable_key"] %>
  secret_key: <%= ENV["secret_key"] %>